savedPath.lecterer.photo=c:/lecterer/picture/upload/
savedPath.lesson.file=c:/lesson/file/upload/
savedPath.message.file=c:/message/file/upload/
savedPath.certificate.file=c:/certificate/file/upload/
savedPath.class.photo=c:/class/picture/upload/